<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>$(NoWarn);CA2007</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="DelegateDecompiler.EntityFrameworkCore5"/>
        <PackageReference Include="FastMember"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite"/>
        <PackageReference Include="Npgsql.NetTopologySuite"/>
        <PackageReference Include="Testcontainers"/>
        <PackageReference Include="Testcontainers.MsSql"/>
        <PackageReference Include="Testcontainers.Oracle"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
        <PackageReference Include="RT.Comb"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="All"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\EFCore.BulkExtensions\EFCore.BulkExtensions.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <None Update="testsettings.local.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="testsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>